### ISSUE TITLE
Android 6/7 clear icon is broken

### ISSUE THREAD

**Issue by oleksandr-dziuban** [thodubois/react-native-woodpicker#10]
Hello @thodubois 
I have noticed that on Android 6 / 7 and on some real devices with Android 8+ clear icon symbol is broken:

![86012](https://user-images.githubusercontent.com/5430640/58636244-84060c80-82f8-11e9-8a0d-a06fb6043d82.png)

What about to change this icon to the symbol "\u2715" to have cross-platform support?
Please check my PR:
#11

**Comment by thodubois** [comment]
Merged. Thanks again!
