### ISSUE TITLE
IphoneX doesn't add extra margin bottom

### ISSUE THREAD

**Issue by bermann** [thodubois/react-native-woodpicker#13]
As you can see in the following image, the native keyboard does add an extra padding:
![image](https://user-images.githubusercontent.com/2607833/60351617-26ff8400-9994-11e9-8616-430272312ac0.png)

But the DatePicker doesn't add it:
![image](https://user-images.githubusercontent.com/2607833/60351234-59f54800-9993-11e9-9b33-585a2e0125e3.png)

**Comment by thodubois** [comment]
Thanks for your contribution!
