### ISSUE TITLE
[IOS] How to change the opacity of the background when opening the DatePicker?

### ISSUE THREAD

**Issue by thiago-sandes** [thodubois/react-native-woodpicker#29]
Expectancy:
![exampleApp](https://user-images.githubusercontent.com/26418631/87431866-9b1bc280-c5bd-11ea-95a5-5de6f6e41595.gif)

Reality:
![Simulator Screen Shot - iPhone 11 - 2020-07-14 at 10 28 04](https://user-images.githubusercontent.com/26418631/87431889-a66eee00-c5bd-11ea-936f-35700215b078.png)

**Comment by thodubois** [comment]
Hello, currently there is no way to do this. The backdrop opacity is manage by an animated value.
https://github.com/thodubois/react-native-woodpicker/blob/3c5392613ea03514a5483b87b2a8394e8a802ec3/components/DatePicker.js#L67
The opacity goes from 0 to 0.5.
I can add a way to custom animated destination value.

**Comment by thodubois** [comment]
Hello, it's done. You can use the 0.2.5 version =)

**Comment by thiago-sandes** [comment]
Thanks 💯
