### ISSUE TITLE
not hide android date picker when click "OK"

### ISSUE THREAD

**Issue by PavelDikiy** [thodubois/react-native-woodpicker#36]
In react-native-woodpicker/components/DatePicker.js / , method handleAndroidDateChange 
there is a commented out code "//togglePicker();". 
I think this is the problem, when I delete the comment, it works well

**Comment by thodubois** [comment]
Wow, How did I let this go...
Thanks, for the comment.

**Comment by thodubois** [comment]
Fixed on 0.2.8 
Thanks again
