### ISSUE TITLE
@react-native-community/picker is deprecated

### ISSUE THREAD

**Issue by 3atharvkurdukar** [thodubois/react-native-woodpicker#41]
As per npm description:

> This library has been renamed to @react-native-picker/picker. See the GitHub new repository: https://github.com/react-native-picker/picker

Please update the package & docs to include this change.

**Comment by thodubois** [comment]
Hello, it's done. You can use the version 0.3.3.

**Comment by PavelDikiy** [comment]
replace the lines in file README.txt, please.
@react-native-community/picker
on
@react-native-picker/picker

**Comment by thodubois** [comment]
Oh yes forgot this 👍
