### ISSUE TITLE
DatePicker not the all area is clickable 

### ISSUE THREAD

**Issue by PavelDikiy** [thodubois/react-native-woodpicker#46]
when added style with height 10 or 100, i can't click on all area (datePicker not opening).
style={{height: 100}}

it worked well in the previous version

**Comment by thodubois** [comment]
Hi,
Could you be more specific? What props did you use ?

**Comment by PavelDikiy** [comment]
`&lt;DatePicker        style={{height: 40,    width: 200,}}         /&gt;`
if the height is 40 or 300 then the clickable area will be about 20 by. The width is taken 100% - it's good here. Height only problems.

**Comment by thodubois** [comment]
You can try the 0.3.5 version. This should be ok =).
Plus, I added a style prop to manage the touchable style

**Comment by PavelDikiy** [comment]
Wonderful, thanks =)
