### ISSUE TITLE
Inconsistency in documentation

### ISSUE THREAD

**Issue by 3atharvkurdukar** [thodubois/react-native-woodpicker#48]
While reading documentation for `DateTimePicker`, I encountered an inconsistency between the example and the props table.
The example uses props `onChange`, `selectedDate`, whereas the props table shows props as `value` and `onDateChange`.

Please make sure to remove this as well as any other consistencies, if present.

**Comment by thodubois** [comment]
Hello, it should be ok now =)
Thank you for your feedback
