### ISSUE TITLE
How to stylize the picker properly?

### ISSUE THREAD

**Issue by 3atharvkurdukar** [thodubois/react-native-woodpicker#51]
I am trying to implement the DatePicker in my app, but it takes a lot of space. It has a huge height. I tried to color these parts to distinguis them. Here's the code and the output:
```javascript
import React, { useState } from 'react';
import { StyleSheet } from 'react-native';
import { DatePicker } from 'react-native-woodpicker';

const Test = () => {
  const [pickedDate, setPickedDate] = useState();

  const handleText = () =>
    pickedDate ? pickedDate.toDateString() : 'No value Selected';

  const handleDateChange = (date) => {
    setPickedDate(date);
  };

  return (
    <DatePicker
      style={styles.picker}
      containerStyle={styles.inputContainer}
      textInputStyle={styles.input}
      value={pickedDate}
      onDateChange={handleDateChange}
      title="Date Picker"
      text={handleText()}
      androidMode="calendar"
      androidDisplay="calendar"
      iosMode="date"
      iosDisplay="inline"
      isNullable
    />
  );
};

export default Test;

const styles = StyleSheet.create({
  picker: {
    backgroundColor: '#E1E1FF',
  },
  inputContainer: {
    backgroundColor: '#D3D3FF',
  },
  input: {
    borderColor: 'rgba(214,214,214,60)',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    width: '100%',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
});
```
![image](https://user-images.githubusercontent.com/19382880/120193245-ce009080-c239-11eb-9255-0124aaf6b094.png)

How do I manage the sizes appropriately? I want it to look like a simple text input.

**Comment by thodubois** [comment]
Hello,

You can see the component as followed:
```js
<View style={containerStyle}>
  <View style={style}>
    <Text style={textInputStyle}>
      {text}
    </Text>
  </View>
</View>
```
So you need to change the style prop for the global input (thats where the touchable part is). 
textInputStyle if you want to change color or font size specificaly.
containerStyle if you want to change wrapper input

by default, those style are eqal to :
```js
style: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    textAlign: "center",
  }
containerStyle: null
textInputStyle: {
    color: "black",
    fontSize: 16,
  }
```

**Comment by 3atharvkurdukar** [comment]
I know this is not related to any bug, but how should I set the height of container to match the height of the touchable? I can't use the absolute values as they might break depending upon the system.

**Comment by thodubois** [comment]
Did you try like the example? https://github.com/thodubois/react-native-woodpicker/blob/db4209a6e549bac778e20ecb61042f529188e17a/example/ExampleApp/App.tsx#L86 
by default the container match the touchable.

**Comment by 3atharvkurdukar** [comment]
There seems to be something weird happening with me, and I don't know why. If I do not define any style, it will just display text and take the width of `TextInput`. However, the moment I define `style`  or `containerStyle`, it takes a huge amount of space, as shown in the images:
| only `input` | `input` & `picker` | `input` & `container`  | `input`, `picker` & `container` |
|:------------:|:-------------------:|:-----------------------:|:--------------------------------:|
|<img src="https://user-images.githubusercontent.com/19382880/120306365-6ad13580-c2ef-11eb-9cc4-70b7d7d883e2.png" /> | <img src="https://user-images.githubusercontent.com/19382880/120306396-74f33400-c2ef-11eb-825e-73cef62a0b5a.png" /> | <img src="https://user-images.githubusercontent.com/19382880/120306465-82a8b980-c2ef-11eb-8431-68c9c6119a06.png" /> | <img src="https://user-images.githubusercontent.com/19382880/120308858-2b581880-c2f2-11eb-839f-d5c8f2ea3d9c.png" /> |

The code is as follows:
```javascript
import React, { useState } from 'react';
import { StyleSheet } from 'react-native';
import { DatePicker } from 'react-native-woodpicker';

const Test = () => {
  const [pickedDate, setPickedDate] = useState();

  const handleText = () =>
    pickedDate ? pickedDate.toDateString() : 'No value Selected';

  const handleDateChange = (date) => {
    setPickedDate(date);
  };

  return (
    <View style={styles.screen}>
      <DatePicker
        style={styles.picker}
        containerStyle={styles.inputContainer}
        textInputStyle={styles.input}
        value={pickedDate}
        onDateChange={handleDateChange}
        title="Date Picker"
        text={handleText()}
        androidMode="calendar"
        androidDisplay="calendar"
        iosMode="date"
        iosDisplay="inline"
        isNullable
      />
    </View>
  );
};

export default Test;

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
    backgroundColor: '#D3D3FF',
  },
  picker: {
    backgroundColor: '#E1E1FF',
  },
  inputContainer: {
    backgroundColor: '#D3D3FF',
  },
  input: {
    borderColor: 'rgba(214,214,214,60)',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    width: '100%',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
});
```

Why does it take so much space, only when it is overridden? I have not provided any value for height or width.

**Comment by thodubois** [comment]
did you try :
```
  style={styles.input}
  containerStyle={styles.inputContainer}
  textInputStyle={styles.picker}
```
You can see here
https://snack.expo.io/@fromwood/test-datepicker
