### ISSUE TITLE
Close DatePicker when date is selected

### ISSUE THREAD

**Issue by lucasmrl** [thodubois/react-native-woodpicker#52]
I've been looking here but I can't figure out the way to do this.
Is it possible to close the Date Picker (ios: compact, android: calendar) when the user selects a date?

**Comment by thodubois** [comment]
Hello, No, it's not possible now. I'll take a look when I can. Don't hesitate to create PR if you want.

**Comment by thodubois** [comment]
Hello, I checked and currently its not possible. I check the datetimepicker docs and the UIDatePicker (ios). I didn't see an event or a callback where a can listen. =/
