### ISSUE TITLE
Change colour of slide up box on Picker

### ISSUE THREAD

**Issue by aidanarmstrong** [thodubois/react-native-woodpicker#54]
Hi not really an issue but is there a way in which we can add a style property to the slide up picker as i would like to enable a dark mode feature to my app but the colour remains "white" i don't see anywhere in the docs about it being able to be changed?

**Comment by thodubois** [comment]
Hello, there is currently no way to do that.
Maybe I could add another style or color props for this part.

**Comment by thodubois** [comment]
Hi, sorry for this long wait. 
I just realized you can do this by setting customProps on you picker:
```jsx
iosCustomProps={{style: {backgroundColor: "black"}, itemStyle:{color:"white"} }}
```

**Comment by Fiyifoluwa** [comment]
Hello! @thodubois, I think it would be nice for you to add this to the docs.

**Comment by Fiyifoluwa** [comment]
This doesn't apply to the android build of my app, instead, it messes up the previous styles. Could you please help with the right props?

**Comment by Fiyifoluwa** [comment]
To clarify, in dark mode on android, the picker has a very dark background and it becomes really hard to make out the content/items in the picker as the color of all the text in the picker is set to black by default

**Comment by Fiyifoluwa** [comment]
To clarify, this happens in mode dialog and not dropdown. I chose to stick with dropdown
