### ISSUE TITLE
Minimum time is not respected 

### ISSUE THREAD

**Issue by Arjanvanmaren** [thodubois/react-native-woodpicker#56]
The minimum time is not respected when setting a minimum date prop.

Is there any chance to fix this?

**Comment by thodubois** [comment]
Hello, could you be more specific? Which platform, the behavior, etc... =)
If it's about iOS 14 inline datepicker, there is an issue in the datetimepicker package currently open : https://github.com/react-native-datetimepicker/datetimepicker/issues/363

**Comment by Arjanvanmaren** [comment]
Hi thanks for the quick response, 

I currently only tested this on android.
 
I found the following in the documentation https://github.com/react-native-datetimepicker/datetimepicker#minimumdate-optional 

"Defines the minimum date that can be selected. Note that on Android, this only works for date mode because TimePicker does not support this."

So I don't think its an issue with this library but a limitation on android. 

I will close this issue now.
