### ISSUE TITLE
Item Object in Items List not found, since its comparing references, not Object values

### ISSUE THREAD

**Issue by arnolicious** [thodubois/react-native-woodpicker#57]
When having a List of Objects and a singular Object, which is identical to one of the Objects in the list, it does not get found, which results in unexpected errors.

I think this would fix the issue, and result in less unexpected errors.

_in Picker.js:_
```
const [selectedItem, setSelectedItem] = useState(
    item
      /* This compares the object references */
      //? items.find((current) => current === item)
      
      /* This compares the object values */
      ? items.find((current) => current.label === item.label && current.value === current.value)
      : isNullable
        ? EMPTY_ITEM
        : items[0],
  );
```

**Comment by thodubois** [comment]
Hi, yes, it shouldn't be a ref compare. 
Thanks for your review, you can try the 0.3.9 version

**Comment by arnolicious** [comment]
Amazing!
Thanks for the quick response and fix!
