### ISSUE TITLE
Add an optional icon on the right

### ISSUE THREAD

**Issue by raufabr** [thodubois/react-native-woodpicker#59]
Hi, 
I'm trying to implement an icon on the right hand side of my Item Picker to indicate to the user that this item is a dropdown. I've got the designs done, but I can't figure out a way to trigger the ItemPicker to open if the user clicks the Icon. 

Example below
<img width="327" alt="Screenshot 2021-07-09 at 20 15 24" src="https://user-images.githubusercontent.com/30205551/125126120-8996c900-e0f2-11eb-87cb-c672174c6ab4.png">

Is there a way to toggle the ItemPicker when the user clicks on the Icon, or alternatively have a prop for iconRight/Left or something similar?

**Comment by thodubois** [comment]
Hello, did you try to use the `InputComponent` prop?
You can customize the button and use the following properties :
```
resetValue,
      togglePicker,
      style,
      text,
      textInputStyle,
      touchableStyle,
      isNullable,
      isCompactHiddenPickerNeeded,
      renderHiddenCompactIOSPicker,
``` 
As an example, the current one is :
```js
import type { InputProps } from "../types";

import React from "react";
import { View, Text, TouchableWithoutFeedback } from "react-native";
import { styles } from "../helpers/stylesHelper";

const InputButton = ({
  resetValue,
  togglePicker,
  style,
  text,
  textInputStyle,
  touchableStyle,
  isNullable,
  isCompactHiddenPickerNeeded,
  renderHiddenCompactIOSPicker,
}: InputProps): JSX.Element => {
  return (
    <View style={[styles.input, style]}>
      {isCompactHiddenPickerNeeded ? (
        <View style={[styles.placeHolderContainerStyle, touchableStyle]}>
          <Text
            style={[styles.placeholderStyle, textInputStyle]}
            numberOfLines={1}
            ellipsizeMode="tail"
          >
            {text}
          </Text>
          {renderHiddenCompactIOSPicker()}
        </View>
      ) : (
        <TouchableWithoutFeedback onPress={togglePicker}>
          <View style={[styles.placeHolderContainerStyle, touchableStyle]}>
            <Text
              style={[styles.placeholderStyle, textInputStyle]}
              numberOfLines={1}
              ellipsizeMode="tail"
            >
              {text}
            </Text>
          </View>
        </TouchableWithoutFeedback>
      )}
      {isNullable && (
        <TouchableWithoutFeedback onPress={resetValue}>
          <View style={styles.resetButtonContainerStyle}>
            <Text style={[styles.resetButtonStyle]}>{"\u2715"}</Text>
          </View>
        </TouchableWithoutFeedback>
      )}
    </View>
  );
};

export default InputButton;
```

**Comment by raufabr** [comment]
Thanks @thodubois this worked for me! I basically tried the same thing but I missed the togglePicker prop (Unless you added it after I created this issue)

**Comment by thodubois** [comment]
Great, no it was here since the beginning =P But I should update the doc to highlight this part

**Comment by raufabr** [comment]
Hi, I know this is a very old ticket but I thought I'd post the solution in case someone finds it useful someday.

  return (
    <Picker
      item={item}
      items={items}
      onItemChange={onItemChange}
      title={title}
      placeholder={placeholder}
      InputComponent={({ togglePicker, text }) => {
        return (
          <TouchableOpacity
            onPress={togglePicker}
            style={[
              styles.pickerContainer,```

              backgroundStyles[`${theme}Background`],
              ,
            ]}>
            <View>
              <Text style={[backgroundStyles[`${theme}Text`], textInputStyle]}>
                {text}
              </Text>
            </View>
            <View style={styles.iconStyle}>
              <Entypo
                name='chevron-down'
                size={20}
                color={theme === 'dark' ? colors.white : colors.dark}
              />
            </View>
          </TouchableOpacity>
        );
      }}
    />
  );
```
