### ISSUE TITLE
update pickedDate when changed props "value"

### ISSUE THREAD

**Issue by PavelDikiy** [thodubois/react-native-woodpicker#61]
Hello!
When i passing default date and update it - pickedDate is not work. Calendar show me today date or the first given date.
We needed update pickedDate when changing props "value"

In fiile DatePicker.tsx add:

   useEffect(() => {
            setPickedDate(value);
    }, [value]);

**Comment by thodubois** [comment]
Hello, should be fix in 0.3.10. Tell me if it's ok =)

**Comment by PavelDikiy** [comment]
Hello!
Sorry to keep you waiting.
Works well
