### ISSUE TITLE
Subdividers in Dropdown?

### ISSUE THREAD

**Issue by arnolicious** [thodubois/react-native-woodpicker#64]
Hi!
Is there a way to add (unselectable) Subdividers into a Picker?
Something like this:
![image](https://user-images.githubusercontent.com/46051866/129948028-faeae907-39a2-41ba-9609-9563a9e26225.png)

**Comment by thodubois** [comment]
Hello,
Not possible right now. Native components don't allow this.
If there is a feature that I missed please tell me. This lib is based on [React-Native-Picker](https://github.com/react-native-picker/picker). So I'm limited by those features.
