### ISSUE TITLE
Invalid UIDatePickerStyle 'default' in IOS RN 0.65

### ISSUE THREAD

**Issue by smervs** [thodubois/react-native-woodpicker#65]
<img width="389" alt="Screen Shot 2021-08-27 at 3 56 05 PM" src="https://user-images.githubusercontent.com/24216164/131094523-01c4881a-db5f-4004-bd8f-cabfeccb1e33.png">

I have this error after upgrading to RN0.65 and set iosDisplay='compact'.

I tried using @react-native-datetimepicker/datetimepicker and set display='compact' and it's working fine.

**Comment by thodubois** [comment]
Hi,
very strange, I'll try to reproduce it. The iosDisplay is forwarded as is on the datetimepicker component.
I'll keep you inform

**Comment by thodubois** [comment]
Hello, sorry for this late answer but it should be fix in 0.3.14 =)
