### ISSUE TITLE
Cancel/OK Button are white

### ISSUE THREAD

**Issue by Xxsource98** [thodubois/react-native-woodpicker#70]
On DatePicker on android (I don't know about ios) it's displaying 'cancel' and 'ok' buttons with white color and they are not visible, but I can press them.

Example Code: 
```
<DatePicker
    value={pickedDate || new Date()}
    onDateChange={(date: Date | null) => setPickedDate(date || new Date())}
    title="Date Picker"
    text={handleText()}
    androidMode="date"
    androidDisplay="calendar"
    iosMode="date"
    iosDisplay="inline"
    minimumDate={new Date(Date.now())}
    textInputStyle={{
        color: '#464646',
        fontSize: 20,
        fontFamily: 'Montserrat Regular',
    }}
    isNullable={true}
    style={styles.input}
/>
```

![251374348_594273221907717_4116997108627501035_n](https://user-images.githubusercontent.com/36642285/139705700-43ee1f80-da02-4602-86cd-973dc3c64809.jpg)

**Comment by thodubois** [comment]
Hello, I can't reproduce =/
What's in `styles.input` ?

**Comment by Xxsource98** [comment]
Sadly Yes, android 10

**Comment by qaws5503** [comment]
Hello, I encounter this issue too! with android 12

**Comment by Xxsource98** [comment]
Oh yeah, with ```androidDisplay="default"``` it works perfect now! Thanks for help!
