### ISSUE TITLE
TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by Pavel-Ananich** [thodubois/react-native-woodpicker#77]
I've installed package, imported it and tried to use as it shown in the docs, but have got an error

![Screenshot 2022-01-03 at 19 02 37](https://user-images.githubusercontent.com/86955927/147952416-3b39f49f-143e-4f00-8847-b7a0f540ca50.png)
![Screenshot 2022-01-03 at 19 02 56](https://user-images.githubusercontent.com/86955927/147952449-3bd31965-7a12-4775-8d97-43096df9945e.png)

**Comment by thodubois** [comment]
Hello, can you details the rest of the code. It seems that `modalData` contains one or more item without label. Or pickedData doesn't have a label property.

**Comment by Pavel-Ananich** [comment]
> Hello, can you details the rest of the code. It seems that `modalData` contains one or more item without label. Or pickedData doesn't have a label property.

Yes, I didn't define label

Also could you tell me, please, if I can get this wheel picker rendered instead of '20kgs'?

![Screenshot 2022-01-04 at 22 01 56](https://user-images.githubusercontent.com/86955927/148110177-d6dc16eb-a15f-44eb-9873-dcd07bf7150a.png)

![Screenshot 2022-01-04 at 21 59 53](https://user-images.githubusercontent.com/86955927/148109956-0d99993b-5536-4bf5-99ca-f08d4efc5cad.png)

Now wheel picker opens when I click on 20kgs, but I need it to be rendered on my modal, without header with titles 'Data Picker' and 'Done'. Like this:


![Screenshot 2022-01-04 at 22 04 22](https://user-images.githubusercontent.com/86955927/148110456-daeef479-18c8-4b5f-af54-43851cce8731.png)

**Comment by thodubois** [comment]
Hello, you can define your own input component, donebar, etc =)
The point of this lib is to include a modal you can customize.

If you want the wheel only. check directly to the native library https://github.com/react-native-picker/picker

**Comment by Pavel-Ananich** [comment]
> Hello, you can define your own input component, donebar, etc =) The point of this lib is to include a modal you can customize.
> 
> If you want the wheel only. check directly to the native library https://github.com/react-native-picker/picker

I decided to use reanimated to create wheel picker on ios and android, thanks
