### ISSUE TITLE
In Android this issue show

### ISSUE THREAD

**Issue by DSarvind** [thodubois/react-native-woodpicker#8]
![Screenshot 2019-04-19 at 1 01 24 PM](https://user-images.githubusercontent.com/14093034/56415089-41d5be00-62aa-11e9-96f2-46e32f714860.png)

**Comment by thodubois** [comment]
Hello,

Could you give more details?

**Comment by DSarvind** [comment]
This issue occur in android device.

import { Picker } from 'react-native-woodpicker'


class SecurityQuestions extends Component {
     constructor(props){
      super(props)
      this.state = {
          pickedData: null,
       
      },
      _that = this
     }

data = [
        { label: "Hello, how are you?", value: 1 },
        { label: "Hi, How are you?", value: 2 },
    ];

handlePicker = data => {
        this.setState({ pickedData: data });
      };

render() {
        const { _answer1, _answer2 } = this.state
        return (
            <TouchableWithoutFeedback onPress= ''>
              <View style = {[AppStyles.container,{ justifyContent: AppColors.justifyContentcenter }]}>
                <ScrollView style={{width: Dimensions.get('window').width, height: Dimensions.get('window').height}}>

      
               <Picker
           onItemChange={this.handlePicker}
           items={this.data}
         title="Set Security Questions"
         placeholder="Select Data"
           item={this.state.pickedData}
          style= {{marginLeft:10,marginTop:12,width: Dimensions.get('window').width-90,}}
          placeholderStyle ={{fontSize:AppColors.fyloFontSizeSmall,color: AppColors.placeHolderColor,fontFamily:"Celias"}}
           androidPickerMode="dropdown"
            isNullable
        />
</ScrollView>
              </View>
            </TouchableWithoutFeedback>
          )
      }

**Comment by thodubois** [comment]
Right, made a mistake on Android render.
Should be good on the 0.0.13 .
