### ISSUE TITLE
Picker Buttons are white and can't be distinguished from background

### ISSUE THREAD

**Issue by Alexp858** [thodubois/react-native-woodpicker#80]
On some Android devices the Picker Buttons "Cancel" and "Ok" aren't visibile because they have the same white color as the background, making them not visible. Not sure what is causing this issue. Everything worked fine on my colleague's phone, and then I noticed this on my phone and on the simulator. When I opened a new simulator on my laptop (the one on the right  in the picture), it seemed to be working just fine. Android versions on both my phone and the simulator that works is 11, so that might not be the reason.
![image](https://user-images.githubusercontent.com/75473920/151331031-ddea2d4d-8405-42fb-81ac-ba3a3af933ea.png)
.

**Comment by thodubois** [comment]
Hello, could you try `androidDisplay="default"`, it seems like there is an issue in the native lib.

**Comment by Alexp858** [comment]
Yeah that fixed it. Thanks for the help
