### ISSUE TITLE
How do you put a chevron down next to the picker data?

### ISSUE THREAD

**Issue by logicman** [thodubois/react-native-woodpicker#85]
Planning to use this for my project and so was wondering how to put a chevron down, right next to where the data is displayed. 

<img width="423" alt="Screenshot 2022-05-24 at 1 15 55 PM" src="https://user-images.githubusercontent.com/449627/169977646-b50c312e-141f-4ae9-a0cf-31ffa9300621.png">

Thank you!

**Comment by thodubois** [comment]
Hello, do you have some code sample?
