### ISSUE TITLE
Large box around regular input

### ISSUE THREAD

**Issue by t3db0t** [thodubois/react-native-woodpicker#91]
I've got `Picker` working as a basic selector (not a Datetime selector) but it has a large hit area around it instead of just around the data (border is my styling):
![IMG_4DE7662FF85F-1](https://user-images.githubusercontent.com/203307/201408505-c9926b5a-1949-47f7-afae-1b47278ef1ce.jpeg)
The examples don't seem to reflect this but I'm not sure what I could be doing wrong as I'm using almost exactly the same code as in the example.
Do I need to use `InputComponent` to control this? Is there documentation on that?

**Comment by thodubois** [comment]
Hello, could you give a sample of code?  
You can use those three props:

style | ViewStyle | false | Configure the input style (View)
-- | -- | -- | --
containerStyle | ViewStyle | false | Configure the input container style (View)
textInputStyle | TextStyle | false | Configure the input text style (Text)

Or yes, use your own component (InputComponent) as the "button" component.
https://github.com/thodubois/react-native-woodpicker#itemcomponent-specific

**Comment by t3db0t** [comment]
Here's the core code—as you can see, it's copied directly from the example (with the exception of usage of `styled-components`)

```
const StyledPicker = styled(Picker)`
  border: 1px solid gray;
`;

export const DeviceView = ({ route, navigation }) => {
  const [currentPickerChannel, setCurrentPickerChannel] = useState();

  const channelItems = [
    {label: "11", value: 11},
    {label: "12", value: 12},
    {label: "13", value: 13},
    {label: "14", value: 14},
    {label: "15", value: 15},
    {label: "16", value: 16},
    {label: "17", value: 17},
    {label: "18", value: 18},
    {label: "19", value: 19},
    {label: "20", value: 20},
    {label: "21", value: 21},
    {label: "22", value: 22},
    {label: "23", value: 23},
    {label: "24", value: 24},
    {label: "25", value: 25},
    {label: "26", value: 26},
  ];

  return <View>
    <ContainerView>
      <Text>Channel</Text>
      <StyledPicker
        item={currentPickerChannel}
        items={channelItems}
        onItemChange={setCurrentPickerChannel}
        title="Channel"
        placeholder="Select Channel"
        isNullable={false}
        //backdropAnimation={{ opacity: 0 }}
        //mode="dropdown"
        //isNullable
        //disable
      />
    </ContainerView>
    <StatusBar style="auto" />
  </View>
}
```

**Comment by t3db0t** [comment]
> You can use those three props

What is the type of `style`, `containerStyle` and `textInputStyle`? Is there an example of what I would put there?

**Comment by thodubois** [comment]
Here is the current InputComponent and where those styles are used:
https://github.com/thodubois/react-native-woodpicker/blob/master/src/components/InputButton.tsx
style: https://github.com/thodubois/react-native-woodpicker/blob/3b6341a1364cedcd4dbff7fe605d96da9644a636/src/components/InputButton.tsx#L19
textInputStyle: https://github.com/thodubois/react-native-woodpicker/blob/3b6341a1364cedcd4dbff7fe605d96da9644a636/src/components/InputButton.tsx#L23

The containerStyle is the view style containing the input and the picker :
android: https://github.com/thodubois/react-native-woodpicker/blob/3b6341a1364cedcd4dbff7fe605d96da9644a636/src/components/AndroidPicker.tsx#L42
ios : https://github.com/thodubois/react-native-woodpicker/blob/3b6341a1364cedcd4dbff7fe605d96da9644a636/src/components/IOSPicker.tsx#L45
