### ISSUE TITLE
Differentiate between change item and selected (Done) item

### ISSUE THREAD

**Issue by t3db0t** [thodubois/react-native-woodpicker#92]
Is there a way to differentiate between changing an item (before Done is pressed) and selecting the item (when Done is pressed)? My app uses a time-consuming async process when an item is chosen and I don't want it running every single time the selector is changed before Done is pressed.

**Comment by thodubois** [comment]
Hello, actually you can't do this. =/ Would you still need a feature like this? Trigger onItemChange only on donePress ?

**Comment by t3db0t** [comment]
Oh—I somehow didn't notice that there IS an `onDonePress`. I think that's all I need!
