### ISSUE TITLE
Remove title indent on Android picker

### ISSUE THREAD

**Issue by DonBranson** [thodubois/react-native-woodpicker#95]
We want to get rid of the indent on the title as seen in the attached image. The available styling options (textInputStyle, containerStyle, style) do not alter the appearance of the popup. Is there a way to get rid of the indent, or align the menu items with the title? The version in question is 0.3.17.

![Screen Shot 2023-01-19 at 3 49 08 PM](https://user-images.githubusercontent.com/80936/213575377-a439cd86-ef78-4854-b03f-5cb06b6bc1cd.png)

**Comment by thodubois** [comment]
Hello,
Sorry but this is the native popup and I didn't check [React native picker](https://www.npmjs.com/package/@react-native-picker/picker) for a while but I think it's still not possible
